CREATE TABLE times
(
   time_id                   DATE          NOT NULL,
   day_name                  VARCHAR2(9)   NOT NULL,
   day_number_in_week        NUMBER(1)     NOT NULL,
   day_number_in_month       NUMBER(2)     NOT NULL,
   calendar_week_number      NUMBER(2)     NOT NULL,
   fiscal_week_number        NUMBER(2)     NOT NULL,
   week_ending_day           DATE          NOT NULL,
   week_ending_day_id        NUMBER        NOT NULL,
   calendar_month_number     NUMBER(2)     NOT NULL,
   fiscal_month_number       NUMBER(2)     NOT NULL,
   calendar_month_desc       VARCHAR2(8)   NOT NULL,
   calendar_month_id         NUMBER        NOT NULL,
   fiscal_month_desc         VARCHAR2(8)   NOT NULL,
   fiscal_month_id           NUMBER        NOT NULL,
   days_in_cal_month         NUMBER        NOT NULL,
   days_in_fis_month         NUMBER        NOT NULL,
   end_of_cal_month          DATE          NOT NULL,
   end_of_fis_month          DATE          NOT NULL,
   calendar_month_name       VARCHAR2(9)   NOT NULL,
   fiscal_month_name         VARCHAR2(9)   NOT NULL,
   calendar_quarter_desc     CHAR(7)       NOT NULL,
   calendar_quarter_id       NUMBER        NOT NULL,
   fiscal_quarter_desc       CHAR(7)       NOT NULL,
   fiscal_quarter_id         NUMBER        NOT NULL,
   days_in_cal_quarter       NUMBER        NOT NULL,
   days_in_fis_quarter       NUMBER        NOT NULL,
   end_of_cal_quarter        DATE          NOT NULL,
   end_of_fis_quarter        DATE          NOT NULL,
   calendar_quarter_number   NUMBER(1)     NOT NULL,
   fiscal_quarter_number     NUMBER(1)     NOT NULL,
   calendar_year             NUMBER(4)     NOT NULL,
   calendar_year_id          NUMBER        NOT NULL,
   fiscal_year               NUMBER(4)     NOT NULL,
   fiscal_year_id            NUMBER        NOT NULL,
   days_in_cal_year          NUMBER        NOT NULL,
   days_in_fis_year          NUMBER        NOT NULL,
   end_of_cal_year           DATE          NOT NULL,
   end_of_fis_year           DATE          NOT NULL,
   CONSTRAINT times_pk
      PRIMARY KEY (time_id)
);